using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using ADOFAI;
using UnityEngine;
using R = System.Reflection;

namespace KineticNapier.ADOFAIMultiTileEditor
{
    internal static class FixedTileDecorationGenerator
    {
        private const string OwnerTag = "adofaiMTEGenerated";
        private const int LayoutColumns = 4;
        private const float PreviewOriginX = 0.5f;
        private const float PreviewOriginY = 2.5f;
        private const float PreviewSpacingX = 3.0f;
        private const float PreviewSpacingY = 2.5f;
        private const double SpeedEpsilon = 1.0e-5;
        private const float PositionEpsilon = 0.0005f;

        internal static TileDecorationResult GenerateAndCommit(scnEditor editor, IList<TrackSlot> tracks, GenerationPlan plan)
        {
            if (editor == null || editor.levelData == null)
                throw new InvalidOperationException("Editor is not ready.");
            if (tracks == null || tracks.Count == 0)
                throw new InvalidOperationException("No source tracks are available for tile decoration generation.");
            if (plan == null)
                throw new InvalidOperationException("No analyzed Multi Tile region is available.");

            LevelData output = editor.levelData.Copy();
            int selectedFloor = GameAngleProbe.TryGetSelectedFloorIndex(editor);
            LevelData candidate = output.Copy();
            TileDecorationResult result = PopulateCandidate(editor, candidate, tracks, plan);

            bool committed = false;
            try
            {
                TrackStore.RestoreSnapshot(editor, candidate, true);
                editor.UpdateDecorationObjects();
                committed = true;
                return result;
            }
            finally
            {
                if (!committed)
                {
                    TrackStore.RestoreSnapshot(editor, output, true);
                    if (selectedFloor >= 0 && selectedFloor < editor.floors.Count)
                        editor.SelectFloor(editor.floors[selectedFloor], true);
                }
            }
        }

        private static TileDecorationResult PopulateCandidate(
            scnEditor editor,
            LevelData candidate,
            IList<TrackSlot> tracks,
            GenerationPlan plan)
        {
            Vector2 outputStartPosition = GetOutputStartPosition(editor, plan.RegionStartFloor);
            LevelData active = editor.levelData.Copy();
            int selectedFloor = GameAngleProbe.TryGetSelectedFloorIndex(editor);
            List<VisualTrack> visuals = CaptureVisualTracks(editor, tracks, active, selectedFloor);

            IList decorations = candidate.decorations as IList;
            if (decorations == null)
                throw new InvalidOperationException("LevelData.decorations is not list-compatible in this game build.");

            int alignedPlanetPairs = AlignAutoGeneratedPlanetPairs(decorations, tracks, visuals);
            int replaced = RemoveOwnedPreviews(decorations);
            int created = 0;
            int skippedTracks = 0;

            for (int t = 0; t < visuals.Count; t++)
            {
                VisualTrack visual = visuals[t];
                if (HasManualCompatiblePreview(decorations, visual.TrackIndex))
                {
                    skippedTracks++;
                    continue;
                }

                Vector2 origin = outputStartPosition + GetPreviewOrigin(visual.TrackIndex);
                for (int i = 0; i < visual.Tiles.Count; i++)
                {
                    decorations.Add(CreateFloorAddObject(visual, visual.Tiles[i], i, origin, plan.RegionStartFloor));
                    created++;
                }
            }

            return new TileDecorationResult
            {
                Created = created,
                Replaced = replaced,
                SkippedTracks = skippedTracks,
                Diagnostic = "Generated " + created + " region-only source Floor decoration(s) from F" + plan.RegionStartFloor
                    + "; replaced " + replaced + " previous MTE tile decoration(s); aligned " + alignedPlanetPairs
                    + " auto-created planet pair(s) to each source region's inherited incoming phase"
                    + (skippedTracks > 0 ? "; preserved manual/EQOL preview(s) on " + skippedTracks + " track(s)." : ".")
            };
        }

        private static List<VisualTrack> CaptureVisualTracks(
            scnEditor editor,
            IList<TrackSlot> tracks,
            LevelData active,
            int selectedFloor)
        {
            var result = new List<VisualTrack>();
            try
            {
                for (int t = 0; t < tracks.Count; t++)
                {
                    TrackSlot slot = tracks[t];
                    if (slot == null || slot.Data == null)
                        throw new InvalidOperationException("Track #" + (t + 1) + " has no source snapshot.");
                    TrackStore.RestoreSnapshot(editor, slot.Data, false);
                    result.Add(CaptureCurrentTrack(editor, slot, t));
                }
            }
            finally
            {
                TrackStore.RestoreSnapshot(editor, active, true);
                if (selectedFloor >= 0 && selectedFloor < editor.floors.Count)
                    editor.SelectFloor(editor.floors[selectedFloor], true);
            }
            return result;
        }

        private static VisualTrack CaptureCurrentTrack(scnEditor editor, TrackSlot slot, int trackIndex)
        {
            if (slot.RegionStartFloor < 0 || slot.RegionStartFloor >= editor.floors.Count)
                throw new InvalidOperationException("Track '" + slot.Name + "' region start is outside its source path.");

            scrFloor requestedStart = editor.floors[slot.RegionStartFloor];
            if (requestedStart == null || requestedStart.midSpin)
                throw new InvalidOperationException("Track '" + slot.Name + "' preview start must be a landable floor.");

            var floors = new List<scrFloor>();
            int regionIndex = -1;
            for (int i = 0; i < editor.floors.Count; i++)
            {
                scrFloor floor = editor.floors[i];
                if (floor == null || floor.midSpin) continue;
                if (ReferenceEquals(floor, requestedStart)) regionIndex = floors.Count;
                floors.Add(floor);
            }

            var visual = new VisualTrack
            {
                TrackIndex = trackIndex,
                Name = slot.Name ?? ("Track " + (trackIndex + 1)),
                BaseBpm = editor.levelData.bpm,
                InitialStepOffset = Vector2.right,
                ForwardStepOffset = Vector2.right
            };

            if (regionIndex < 0 || regionIndex + 1 >= floors.Count) return visual;

            float tileSize = ResolveTileSize();
            Vector2 startPosition = ToLevelPosition(floors[regionIndex], tileSize);
            Vector2 firstPosition = ToLevelPosition(floors[regionIndex + 1], tileSize);
            Vector2 forwardStep = firstPosition - startPosition;
            if (forwardStep.sqrMagnitude > 1.0e-8f) visual.ForwardStepOffset = forwardStep;

            // Starting in the middle of a chart is different from starting at F0.
            // At a landed floor, the non-pivot planet is still on the incoming/previous
            // tile. Seeding it from the next tile mirrors the whole orbit path and makes
            // the pair appear to travel backwards. Preserve the old F0 fallback, but for
            // a mid-chart region inherit the actual incoming planet phase.
            if (regionIndex > 0)
            {
                Vector2 previousPosition = ToLevelPosition(floors[regionIndex - 1], tileSize);
                Vector2 incomingStep = previousPosition - startPosition;
                if (incomingStep.sqrMagnitude > 1.0e-8f) visual.InitialStepOffset = incomingStep;
            }
            else
            {
                visual.InitialStepOffset = visual.ForwardStepOffset;
            }

            // F0 has no incoming tile and keeps the historical endpoint-only preview.
            // For a mid-chart region the selected start floor is a real corner/straight
            // tile with incoming geometry, so include it instead of silently dropping the
            // first selected tile. The synthetic terminal floor is still omitted.
            int previewStart = regionIndex > 0 ? regionIndex : regionIndex + 1;
            for (int i = previewStart; i + 1 < floors.Count; i++)
            {
                scrFloor floor = floors[i];
                scrFloor previous = i > 0 ? floors[i - 1] : floor;
                float visualAngle = GetVisualTrackAngle(floor);
                float rhythmAngle = GetRhythmAngle(floor);
                float rotation = GetTrackRotation(floor, visualAngle);
                double speed = ReadDouble(floor, "speed", 1.0);
                double previousSpeed = ReadDouble(previous, "speed", 1.0);

                visual.Tiles.Add(new VisualTile
                {
                    LocalPosition = ToLevelPosition(floor, tileSize) - startPosition,
                    RotationDegrees = rotation,
                    TrackAngleDegrees = visualAngle,
                    RhythmAngleDegrees = rhythmAngle,
                    Speed = speed,
                    PreviousSpeed = previousSpeed
                });
            }
            return visual;
        }

        private static int AlignAutoGeneratedPlanetPairs(IList decorations, IList<TrackSlot> tracks, IList<VisualTrack> visuals)
        {
            int aligned = 0;
            int count = Math.Min(tracks.Count, visuals.Count);
            for (int i = 0; i < count; i++)
            {
                TrackSlot slot = tracks[i];
                VisualTrack visual = visuals[i];
                if (slot == null || visual == null || !slot.TagsReady) continue;

                LevelEvent planetA = FindPlanetAddObject(decorations, slot.PlanetATag);
                LevelEvent planetB = FindPlanetAddObject(decorations, slot.PlanetBTag);
                if (planetA == null || planetB == null) continue;

                LevelEvent pivot = slot.PivotIsA ? planetA : planetB;
                LevelEvent moving = slot.PivotIsA ? planetB : planetA;
                Vector2 center = GetPreviewOrigin(i);
                Vector2 legacyMoving = center + Vector2.left;
                Vector2 oldForwardMoving = center + visual.ForwardStepOffset;
                Vector2 desiredMoving = center + visual.InitialStepOffset;

                if (!IsTileRelativePlanet(planetA) || !IsTileRelativePlanet(planetB)) continue;
                if (!Approximately(ReadVector2(pivot, "position", new Vector2(float.NaN, float.NaN)), center)) continue;

                Vector2 movingPosition = ReadVector2(moving, "position", new Vector2(float.NaN, float.NaN));
                if (!Approximately(movingPosition, legacyMoving)
                    && !Approximately(movingPosition, oldForwardMoving)
                    && !Approximately(movingPosition, desiredMoving)) continue;

                SetTypedData(pivot, "position", center);
                SetTypedData(moving, "position", desiredMoving);
                aligned++;
            }
            return aligned;
        }

        private static LevelEvent FindPlanetAddObject(IList decorations, string requestedTag)
        {
            LevelEvent found = null;
            string target = (requestedTag ?? "").Trim();
            if (target.Length == 0) return null;
            for (int i = 0; i < decorations.Count; i++)
            {
                LevelEvent ev = decorations[i] as LevelEvent;
                if (ev == null || !IsEventNamed(ev, "AddObject")) continue;
                string objectType = Convert.ToString(SafeGetData(ev, "objectType"), CultureInfo.InvariantCulture) ?? "";
                if (!string.Equals(objectType, "Planet", StringComparison.OrdinalIgnoreCase)) continue;
                string tag = Convert.ToString(SafeGetData(ev, "tag"), CultureInfo.InvariantCulture) ?? "";
                if (!string.Equals(tag.Trim(), target, StringComparison.Ordinal)) continue;
                if (found != null) return null;
                found = ev;
            }
            return found;
        }

        private static bool IsTileRelativePlanet(LevelEvent ev)
        {
            string relativeTo = Convert.ToString(SafeGetData(ev, "relativeTo"), CultureInfo.InvariantCulture) ?? "";
            return string.Equals(relativeTo, "Tile", StringComparison.OrdinalIgnoreCase);
        }

        private static Vector2 ReadVector2(LevelEvent ev, string key, Vector2 fallback)
        {
            object value = SafeGetData(ev, key);
            if (value is Vector2) return (Vector2)value;
            if (value is Vector3) { Vector3 v = (Vector3)value; return new Vector2(v.x, v.y); }
            return fallback;
        }

        private static bool Approximately(Vector2 a, Vector2 b)
        {
            if (float.IsNaN(a.x) || float.IsNaN(a.y) || float.IsNaN(b.x) || float.IsNaN(b.y)) return false;
            return (a - b).sqrMagnitude <= PositionEpsilon * PositionEpsilon;
        }

        private static LevelEvent CreateFloorAddObject(VisualTrack visual, VisualTile tile, int tileIndex, Vector2 origin, int outputFloor)
        {
            LevelEvent ev = CreateCustomEvent("AddObject", outputFloor);
            int rhythmKey = (int)Math.Round(tile.RhythmAngleDegrees * 10000.0, MidpointRounding.AwayFromZero);
            string baseTag = "T" + visual.TrackIndex;
            string tag = baseTag + " " + baseTag + "_" + tileIndex
                + " qolMultiTile_" + baseTag
                + " qolMultiTileRhythm_" + rhythmKey.ToString(CultureInfo.InvariantCulture)
                + " " + OwnerTag;

            SetRequiredData(ev, "objectType", "Floor");
            SetRequiredData(ev, "tag", tag);
            SetRequiredData(ev, "position", origin + tile.LocalPosition);
            SetRequiredData(ev, "relativeTo", "Global");
            SetRequiredData(ev, "rotation", tile.RotationDegrees);
            SetRequiredData(ev, "trackAngle", tile.TrackAngleDegrees);
            SetOptionalData(ev, "depth", tileIndex);
            SetOptionalData(ev, "scale", new Vector2(100f, 100f));
            SetOptionalData(ev, "lockRotation", false);
            SetOptionalData(ev, "lockScale", false);
            SetOptionalData(ev, "pivotOffset", Vector2.zero);
            SetOptionalData(ev, "parallax", Vector2.zero);
            SetOptionalData(ev, "parallaxOffset", Vector2.zero);
            SetOptionalData(ev, "syncFloorDepth", false);
            SetOptionalData(ev, "trackType", "Normal");
            SetOptionalData(ev, "trackStyle", "Standard");
            SetOptionalData(ev, "trackColorType", "Single");
            SetOptionalData(ev, "trackColor", "debb7b");
            SetOptionalData(ev, "secondaryTrackColor", "ffffff");
            SetOptionalData(ev, "trackGlowEnabled", false);
            SetOptionalData(ev, "trackGlowColor", "ffffff");
            SetOptionalData(ev, "trackOpacity", 100f);
            SetOptionalData(ev, "trackIcon", SpeedIcon(tile.PreviousSpeed, tile.Speed));
            SetOptionalData(ev, "trackIconAngle", 0f);
            SetOptionalData(ev, "trackIconFlipped", false);
            SetOptionalData(ev, "trackIconOutlines", false);
            SetOptionalData(ev, "trackGraySetSpeedIcon", false);
            SetOptionalData(ev, "trackSetSpeedIconBpm", visual.BaseBpm * tile.Speed);
            return ev;
        }

        private static Vector2 GetOutputStartPosition(scnEditor editor, int regionStartFloor)
        {
            if (editor.floors == null || regionStartFloor < 0 || regionStartFloor >= editor.floors.Count || editor.floors[regionStartFloor] == null)
                throw new InvalidOperationException("Generated output has no runtime floor at the Multi Tile start F" + regionStartFloor + ".");
            return ToLevelPosition(editor.floors[regionStartFloor], ResolveTileSize());
        }

        private static float ResolveTileSize()
        {
            float tileSize = ADOBase.controller == null ? 1f : ADOBase.controller.tileSize;
            return Mathf.Abs(tileSize) < 0.000001f ? 1f : tileSize;
        }

        private static Vector2 ToLevelPosition(scrFloor floor, float tileSize)
        {
            Vector3 p = floor.transform.position;
            return new Vector2(p.x / tileSize, p.y / tileSize);
        }

        private static float GetVisualTrackAngle(scrFloor floor)
        {
            float entryDirection = NormalizeDegrees(90f - (float)(floor.entryangle * Mathf.Rad2Deg));
            float exitDirection = NormalizeDegrees(90f - (float)(floor.exitangle * Mathf.Rad2Deg));
            float difference = Mathf.Abs(exitDirection - entryDirection);
            return difference > 180f ? 360f - difference : difference;
        }

        private static float GetRhythmAngle(scrFloor floor)
        {
            double moved = scrMisc.GetAngleMoved(floor.entryangle, floor.exitangle, !floor.isCCW);
            if (Math.Abs(moved) <= 0.000001d) return 360f;
            return Mathf.Rad2Deg * (float)moved;
        }

        private static float GetTrackRotation(scrFloor floor, float visualAngle)
        {
            float entryDirection = NormalizeDegrees(90f - (float)(floor.entryangle * Mathf.Rad2Deg));
            float exitDirection = NormalizeDegrees(90f - (float)(floor.exitangle * Mathf.Rad2Deg));
            float rotation;
            if (entryDirection > exitDirection)
                rotation = entryDirection - exitDirection > 180f ? entryDirection : exitDirection;
            else
                rotation = exitDirection - entryDirection > 180f ? exitDirection : entryDirection;
            return NormalizeSignedDegrees(rotation + visualAngle + 180f);
        }

        private static float NormalizeDegrees(float value)
        {
            float normalized = Mathf.Repeat(value, 360f);
            return Mathf.Abs(normalized) < 0.000001f ? 0f : normalized;
        }

        private static float NormalizeSignedDegrees(float value)
        {
            float normalized = Mathf.Repeat(value + 180f, 360f) - 180f;
            return Mathf.Abs(normalized) < 0.000001f ? 0f : normalized;
        }

        private static Vector2 GetPreviewOrigin(int trackIndex)
        {
            int col = trackIndex % LayoutColumns;
            int row = trackIndex / LayoutColumns;
            return new Vector2(PreviewOriginX + col * PreviewSpacingX, PreviewOriginY - row * PreviewSpacingY);
        }

        private static string SpeedIcon(double previousSpeed, double speed)
        {
            if (previousSpeed <= SpeedEpsilon || speed <= SpeedEpsilon) return "None";
            double ratio = speed / previousSpeed;
            if (Math.Abs(ratio - 2.0) <= SpeedEpsilon) return "DoubleRabbit";
            if (Math.Abs(ratio - 0.5) <= SpeedEpsilon) return "DoubleSnail";
            return "None";
        }

        private static int RemoveOwnedPreviews(IList decorations)
        {
            int removed = 0;
            for (int i = decorations.Count - 1; i >= 0; i--)
            {
                LevelEvent ev = decorations[i] as LevelEvent;
                if (ev == null || !IsEventNamed(ev, "AddObject")) continue;
                string objectType = Convert.ToString(SafeGetData(ev, "objectType"), CultureInfo.InvariantCulture) ?? "";
                if (!string.Equals(objectType, "Floor", StringComparison.OrdinalIgnoreCase)) continue;
                string tag = Convert.ToString(SafeGetData(ev, "tag"), CultureInfo.InvariantCulture) ?? "";
                if (tag.IndexOf(OwnerTag, StringComparison.Ordinal) < 0) continue;
                decorations.RemoveAt(i);
                removed++;
            }
            return removed;
        }

        private static bool HasManualCompatiblePreview(IList decorations, int trackIndex)
        {
            string marker = "qolMultiTile_T" + trackIndex;
            for (int i = 0; i < decorations.Count; i++)
            {
                LevelEvent ev = decorations[i] as LevelEvent;
                if (ev == null || !IsEventNamed(ev, "AddObject")) continue;
                string objectType = Convert.ToString(SafeGetData(ev, "objectType"), CultureInfo.InvariantCulture) ?? "";
                if (!string.Equals(objectType, "Floor", StringComparison.OrdinalIgnoreCase)) continue;
                string tag = Convert.ToString(SafeGetData(ev, "tag"), CultureInfo.InvariantCulture) ?? "";
                if (tag.IndexOf(OwnerTag, StringComparison.Ordinal) >= 0) continue;
                if (tag.IndexOf(marker, StringComparison.Ordinal) >= 0) return true;
            }
            return false;
        }

        private static LevelEvent CreateCustomEvent(string requestedName, int floor)
        {
            LevelEventInfo info = ResolveEventInfo(requestedName);
            return new LevelEvent(floor, info.type, info);
        }

        private static LevelEventInfo ResolveEventInfo(string requestedName)
        {
            if (GCS.levelEventsInfo == null)
                throw new InvalidOperationException("ADOFAI level-event metadata is not initialized.");
            LevelEventInfo direct;
            if (GCS.levelEventsInfo.TryGetValue(requestedName, out direct) && direct != null) return direct;

            string target = NormalizeEventName(requestedName);
            LevelEventInfo suffixMatch = null;
            foreach (KeyValuePair<string, LevelEventInfo> pair in GCS.levelEventsInfo)
            {
                LevelEventInfo info = pair.Value;
                if (info == null) continue;
                string keyNormalized = NormalizeEventName(pair.Key);
                string infoNormalized = NormalizeEventName(info.name);
                if (keyNormalized == target || infoNormalized == target) return info;
                if (keyNormalized.EndsWith(target, StringComparison.Ordinal)
                    || infoNormalized.EndsWith(target, StringComparison.Ordinal)) suffixMatch = info;
            }
            if (suffixMatch != null) return suffixMatch;
            throw new InvalidOperationException("PACL2 event metadata '" + requestedName + "' is unavailable. Make sure PACL2 is loaded before generating.");
        }

        private static string NormalizeEventName(string value)
        {
            if (string.IsNullOrEmpty(value)) return "";
            var sb = new StringBuilder(value.Length);
            for (int i = 0; i < value.Length; i++)
            {
                char c = value[i];
                if (char.IsLetterOrDigit(c)) sb.Append(char.ToLowerInvariant(c));
            }
            return sb.ToString();
        }

        private static bool IsEventNamed(LevelEvent ev, string requestedName)
        {
            if (ev == null) return false;
            string target = NormalizeEventName(requestedName);
            string infoName = ev.info != null ? NormalizeEventName(ev.info.name) : "";
            if (infoName == target || infoName.EndsWith(target, StringComparison.Ordinal)) return true;
            return NormalizeEventName(ev.eventType.ToString()) == target;
        }

        private static void SetRequiredData(LevelEvent ev, string key, object value)
        {
            if (ev == null || ev.info == null || ev.info.propertiesInfo == null || !ev.info.propertiesInfo.ContainsKey(key))
                throw new InvalidOperationException("Event '" + EventDisplayName(ev) + "' has no property '" + key + "'.");
            SetTypedData(ev, key, value);
        }

        private static void SetOptionalData(LevelEvent ev, string key, object value)
        {
            if (ev == null || ev.info == null || ev.info.propertiesInfo == null || !ev.info.propertiesInfo.ContainsKey(key)) return;
            SetTypedData(ev, key, value);
        }

        private static void SetTypedData(LevelEvent ev, string key, object value)
        {
            object current = SafeGetData(ev, key);
            Type targetType = current != null ? current.GetType() : null;
            if (targetType == null && ev.info != null && ev.info.propertiesInfo != null)
            {
                ADOFAI.PropertyInfo propertyInfo;
                if (ev.info.propertiesInfo.TryGetValue(key, out propertyInfo)
                    && propertyInfo != null && propertyInfo.value_default != null)
                    targetType = propertyInfo.value_default.GetType();
            }
            ev[key] = targetType == null ? value : ConvertFor(value, targetType);
            if (ev.disabled != null && ev.disabled.ContainsKey(key)) ev.disabled[key] = false;
        }

        private static object SafeGetData(LevelEvent ev, string key)
        {
            if (ev == null) return null;
            try { return ev[key]; } catch { return null; }
        }

        private static string EventDisplayName(LevelEvent ev)
        {
            if (ev == null) return "<null>";
            if (ev.info != null && !string.IsNullOrEmpty(ev.info.name)) return ev.info.name;
            return ev.eventType.ToString();
        }

        private static object ConvertFor(object value, Type targetType)
        {
            if (value == null || targetType == null) return value;
            Type actualTarget = Nullable.GetUnderlyingType(targetType) ?? targetType;
            if (actualTarget.IsInstanceOfType(value)) return value;
            if (actualTarget.IsEnum)
            {
                string text = Convert.ToString(value, CultureInfo.InvariantCulture);
                return Enum.Parse(actualTarget, text, true);
            }
            if (actualTarget == typeof(string)) return Convert.ToString(value, CultureInfo.InvariantCulture);
            if (actualTarget == typeof(Vector2) && value is Vector2) return value;
            return Convert.ChangeType(value, actualTarget, CultureInfo.InvariantCulture);
        }

        private static object ReadMember(object target, string name)
        {
            if (target == null) return null;
            Type type = target.GetType();
            const R.BindingFlags flags = R.BindingFlags.Instance | R.BindingFlags.Public | R.BindingFlags.NonPublic;
            try { R.PropertyInfo p = type.GetProperty(name, flags); if (p != null && p.GetIndexParameters().Length == 0) return p.GetValue(target, null); } catch { }
            try { R.FieldInfo f = type.GetField(name, flags); if (f != null) return f.GetValue(target); } catch { }
            return null;
        }

        private static double ReadDouble(object target, string name, double fallback)
        {
            object value = ReadMember(target, name);
            if (value == null) return fallback;
            try { return Convert.ToDouble(value, CultureInfo.InvariantCulture); } catch { return fallback; }
        }

        private sealed class VisualTrack
        {
            internal int TrackIndex;
            internal string Name;
            internal double BaseBpm;
            internal Vector2 InitialStepOffset;
            internal Vector2 ForwardStepOffset;
            internal readonly List<VisualTile> Tiles = new List<VisualTile>();
        }

        private sealed class VisualTile
        {
            internal Vector2 LocalPosition;
            internal double RotationDegrees;
            internal double TrackAngleDegrees;
            internal double RhythmAngleDegrees;
            internal double Speed;
            internal double PreviousSpeed;
        }
    }
}
